// ********RoostGPT********
/*
Test generated by RoostGPT for test integration-report using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=579264a708
ROOST_METHOD_SIG_HASH=809947a8ba

 ########## Scenario ########## 

{
  feature: 'Feature: Petstore E2E Flow\r\n' +
    '    As a user of the Petstore API\r\n' +
    '    I want to manage pets, orders, and user accounts\r\n' +
    '    So that I can run a successful pet store business',
  background: 'Background:\r\n' +
    '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
    '        And I have valid API credentials\r\n' +
    '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
  rule: null,
  scenario: {
    title: 'Scenario: Bulk operations',
    steps: 'Given I have multiple users to create\r\n' +
      'When I create users with array input\r\n' +
      '            | username  | email          | firstName | lastName |\r\n' +
      '            | bulkuser1 | bulk1@test.com | Bulk      | User1    |\r\n' +
      '            | bulkuser2 | bulk2@test.com | Bulk      | User2    |\r\n' +
      'Then all users should be created successfully\r\n' +
      'Given I have multiple pets to add\r\n' +
      'When I add the following pets:\r\n' +
      '            | name    | category | status    |\r\n' +
      '            | Max     | Dog      | available |\r\n' +
      '            | Charlie | Dog      | available |\r\n' +
      'Then all pets should be added successfully',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import io.restassured.http.ContentType;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.restassured.specification.ResponseSpecification;

public class BulkOperationsTest {
    String APIRoutes;
    RequestSpecification reqSpec;
    ResponseSpecification resSpec;
    File payloadDataFile = new File("src"+File.separator+"test"+File.separator+"java"+File.separator+"com"+File.separator+"bootexample4"+File.separator+"RoostTest"+File.separator+"BulkOperationsTest.csv");
    List<Map<String, Object>> API_LIST;
    
    @BeforeEach     
    public void setup() throws Exception {
        API_LIST = new ArrayList<>();
        Files.lines(Paths.get(payloadDataFile.toURI()))
        .skip(1) //skip headers
        .forEach(line -> {
            String[] row = line.split("\\^\\|\\^"); 
            if(row.length > 0 && row[2] != null && row[3] != null && row[4] != null) {
                Map<String, Object> currAPI = new HashMap<>();
                currAPI.put("METHOD", row[0]);
                currAPI.put("URL", row[1]);
                currAPI.put("REQ_HEADERS", JsonParser.parseString(row[2]).getAsJsonObject());
                currAPI.put("REQ_BODY", JsonParser.parseString(row[3]).getAsJsonArray());
                currAPI.put("RESPONSE_CODE", Integer.parseInt(row[4]));
                currAPI.put("RESPONSE_BODY", JsonParser.parseString(row[5]).getAsJsonObject());
                API_LIST.add(currAPI);
            }
        });

        reqSpec = new RequestSpecification();
        resSpec = new ResponseSpecification();
    }

    @Test
    public void testBulkOperations() {
        for (Map<String, Object> API_ROUTE : API_LIST) {
          String URL = API_ROUTE.get("URL").toString();
          String METHOD = API_ROUTE.get("METHOD").toString();
          JsonObject REQ_HEADERS = (JsonObject) API_ROUTE.get("REQ_HEADERS");
          JsonElement REQ_BODY = (JsonElement) API_ROUTE.get("REQ_BODY"); 
          int RESPONSE_CODE = (int) API_ROUTE.get("RESPONSE_CODE");
          JsonObject RESPONSE_BODY = (JsonObject) API_ROUTE.get("RESPONSE_BODY");

          //Setup headers
          for(Map.Entry<String, JsonElement> header : REQ_HEADERS.entrySet()) {
            reqSpec.header(header.getKey(), header.getValue().getAsString());
          }
          
          reqSpec.body(REQ_BODY.toString()).contentType(ContentType.JSON);
          
          switch(METHOD) {
            case "post":
                resSpec = given()
                    .spec(reqSpec)
                    .when()
                    .post(URL);
                break;
            //Put more HTTP Method types here
            //...
            default:
                //unsupported HTTP METHOD
          }

          //Verify response code
          resSpec.then()
                .assertThat()
                .statusCode(RESPONSE_CODE);

          //Verify response body
          for(Map.Entry<String, JsonElement> responseBodyProperty : RESPONSE_BODY.entrySet()) {
            if(!responseBodyProperty.getValue().isJsonNull())
                resSpec.then()
                    .assertThat()
                    .body(responseBodyProperty.getKey(), equalTo(JsonParser.parseString(responseBodyProperty.getValue().toString())));
          }
        }
    }
}
