// ********RoostGPT********
/*
Test generated by RoostGPT for test integration-report using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=b08a92f4b9
ROOST_METHOD_SIG_HASH=d2e5b25f26

 ########## Scenario ########## 

{
  feature: 'Feature: Petstore E2E Flow\r\n' +
    '    As a user of the Petstore API\r\n' +
    '    I want to manage pets, orders, and user accounts\r\n' +
    '    So that I can run a successful pet store business',
  background: 'Background:\r\n' +
    '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
    '        And I have valid API credentials\r\n' +
    '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
  rule: null,
  scenario: {
    title: 'Scenario: Complete pet store management flow',
    steps: 'Given I create a new user with the following details:\r\n' +
      '            | username  | email          | firstName | lastName | password | phone      |\r\n' +
      '            | testuser1 | test@email.com | Test      | User     | pass123  | 1234567890 |\r\n' +
      'When I log in with username "testuser1" and password "pass123"\r\n' +
      'Then I should receive a valid authentication token\r\n' +
      'And the response should include rate limit headers\r\n' +
      '\r\n' +
      '        # Pet Management\r\n' +
      'Given I have a new pet with the following details:\r\n' +
      '            | name   | category | status    |\r\n' +
      '            | Fluffy | Cat      | available |\r\n' +
      'When I add the new pet to the store\r\n' +
      'Then the pet should be successfully created\r\n' +
      'And I can retrieve the pet by its ID\r\n' +
      '\r\n' +
      '        # Upload Pet Image\r\n' +
      'When I upload an image for the pet\r\n' +
      'Then the image should be successfully attached to the pet\r\n' +
      '\r\n' +
      '        # Update Pet\r\n' +
      `When I update the pet's status to "pending"\r\n` +
      "Then the pet's status should be updated successfully\r\n" +
      '\r\n' +
      '        # Find Pets\r\n' +
      'When I search for pets with status "pending"\r\n' +
      'Then the response should include my pet\r\n' +
      'When I search for pets by tag "friendly"\r\n' +
      'Then the search results should be returned successfully\r\n' +
      '\r\n' +
      '        # Store Operations\r\n' +
      'When I check the store inventory\r\n' +
      'Then I should see the current stock levels\r\n' +
      '\r\n' +
      '        # Order Management\r\n' +
      'Given I want to place an order for the pet\r\n' +
      'When I create an order with the following details:\r\n' +
      '            | quantity | shipDate | status |\r\n' +
      '            | 1        | tomorrow | placed |\r\n' +
      'Then the order should be created successfully\r\n' +
      'And I can retrieve the order by its ID\r\n' +
      '\r\n' +
      '        # Order Completion\r\n' +
      'When I approve the order\r\n' +
      'Then the order status should change to "approved"\r\n' +
      'When the order is delivered\r\n' +
      'Then the order status should change to "delivered"\r\n' +
      '\r\n' +
      '        # Cleanup\r\n' +
      'When I delete the order\r\n' +
      'Then the order should be removed successfully\r\n' +
      'When I delete the pet\r\n' +
      'Then the pet should be removed successfully\r\n' +
      'When I delete the user account\r\n' +
      'Then the user should be removed successfully\r\n' +
      'When I attempt to log out\r\n' +
      'Then I should be successfully logged out',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CompletePetStoreManagementFlowTest {
    private static List<String[]> payloads;

    @BeforeAll
    public static void setup() {
        try {
            var filePath = "src/test/java/com/bootexample4/RoostTest/CompletePetStoreManagementFlowTest.csv";
            var reader = new BufferedReader(new FileReader(filePath));
            payloads = new ArrayList<>();
            String row;
            while ((row = reader.readLine()) != null) {
                var data = row.split("\\^\\|\\^");
                payloads.add(data);
            }
            reader.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    @Order(1)
    public void createUserTest() {
        String[] payload = payloads.get(0);
        var response = given().header("Content-Type", "application/json")
                .body(payload[3])
                .when().post(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(2)
    public void loginUserTest() {
        String[] payload = payloads.get(1);
        var response = given().header("Content-Type", "application/json")
                .when().get(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(3)
    public void createPetTest() {
        String[] payload = payloads.get(2);
        var response = given().header("Content-Type", "application/json").header("oauth2", "write:pets")
                .body(payload[3])
                .when().post(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(4)
    public void getPetTest() {
        String[] payload = payloads.get(3);
        var response = given().header("apiKey", "api_key")
                .when().get(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(5)
    public void updatePetTest() {
        String[] payload = payloads.get(4);
        var response = given().header("Content-Type", "application/json").header("oauth2", "write:pets")
                .body(payload[3])
                .when().post(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(6)
    public void getPetByStatusTest() {
        String[] payload = payloads.get(5);
        var response = given().header("oauth2", "write:pets").queryParam("status","pending")
                .when().get(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(7)
    public void createOrderTest() {
        String[] payload = payloads.get(6);
        var response = given().header("Content-Type", "application/json")
                .body(payload[3])
                .when().post(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(), payload[5]);
    }

    @Test
    @Order(8)
    public void getOrderTest() {
        String[] payload = payloads.get(7);
        var response = given().header("Content-Type", "application/json")
                .when().get(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(), payload[5]);
    }

    @Test
    @Order(9)
    public void deleteOrderTest() {
        String[] payload = payloads.get(8);
        var response = given()
                .when().delete(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(10)
    public void deleteUserTest() {
        String[] payload = payloads.get(9);
        var response = given()
                .when().delete(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }

    @Test
    @Order(11)
    public void logoutUserTest() {
        String[] payload = payloads.get(10);
        var response = given().header("Content-Type", "application/json")
                .when().get(payload[1])
                .then().assertThat().statusCode(Integer.parseInt(payload[4])).extract().response();
        assertEquals(response.asString(),payload[5]);
    }
}
