# ********RoostGPT********

# Test generated by RoostGPT for test java-test-analysis using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test generated by RoostGPT for test java-test-analysis using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test generated by RoostGPT for test java-test-analysis using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test generated by RoostGPT for test java-test-analysis using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /availabilityCheck_post for http method type POST 
# RoostTestHash=11e354dac0
# 
# 

# ********RoostGPT********
Feature: Test /availabilityCheck POST endpoint

  Background:
    * def urlBase = karate.properties['test_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['test_AUTH_TOKEN']) }

  Scenario Outline: Validate /availabilityCheck POST endpoint with valid and invalid responses
    Given path '/availabilityCheck'
    And request
      """
      {}
      """
    When method post
    Then status <statusCode>
    And match response ==
      """
      <expectedResponse>
      """

    Examples:
      | statusCode | expectedResponse                                                                                                                                                                                                                                                      |
      |        200 | { control: { type: '#string', message: '#string', code: '#string' }, resource: { resource: { inventoryId: '#number', maxBandwidth: '#number', availabilityType: '#number', availabilityCode: '#number', availabilityDescription: '#string', products: '#object' } } } |
      |        400 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        401 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        403 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        404 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        429 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        500 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        503 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
      |        504 | { type: '#string', message: '#string', code: '#string' }                                                                                                                                                                                                              |
